const screens={splash:document.getElementById('splashScreen'),code:document.getElementById('codeScreen'),guideIntro:document.getElementById('guideIntroScreen'),guide:document.getElementById('guideScreen'),category:document.getElementById('categoryScreen'),game:document.getElementById('gameScreen'),result:document.getElementById('resultScreen')};
function showScreen(name){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[name].classList.add('active');window.scrollTo(0,0)}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function typeText(el,text,speed=28){el.textContent='';for(const ch of text){el.textContent+=ch;await sleep(speed)}}
const questionText=document.getElementById('questionText'),answerText=document.getElementById('answerText'),processText=document.getElementById('processText'),yesWrap=document.getElementById('yesWrap'),yesButton=document.getElementById('yesButton'),cursor=document.getElementById('cursor');let splashUsed=false;
screens.splash.addEventListener('click',async()=>{if(splashUsed)return;splashUsed=true;showScreen('code');await sleep(450);await typeText(questionText,'Hello visitor, would you like to learn how to avoid phishing and scams?',32);cursor.style.display='none';yesWrap.classList.remove('hidden')});
yesButton.addEventListener('click',async()=>{yesButton.disabled=true;yesWrap.classList.add('hidden');await typeText(answerText,'Yes',85);await sleep(250);for(let i=0;i<3;i++){processText.textContent='Processing'+'.'.repeat(i+1);await sleep(650)}await sleep(450);showScreen('guideIntro')});
screens.guideIntro.addEventListener('click',()=>{currentGuide=0;loadGuideCard(true);showScreen('guide')});
const guideCards=[
{title:'How to Stay Safe from Phishing and Scams',body:'Scammers often try to make messages look real so that you act quickly without thinking. Before clicking, replying, downloading, or sharing information, look for warning signs.'},
{title:'1. Check Who Sent It',body:"Always look carefully at the sender's email address, phone number, or account name. A scammer may use a name that looks familiar while using a strange or fake address.\n\nExample: A message says it is from Apple, but the email address is applehelp247@gmail.com."},
{title:'2. Be Careful with Urgent Messages',body:'Scammers often try to scare you or rush you.\n\nWatch out for messages like:\n• “Your account will be deleted today!”\n• “Pay immediately!”\n• “You have only 10 minutes to respond!”\n• “Your account has been hacked!”\n\nTake your time and check whether the message is real.'},
{title:'3. Think Before You Click',body:"Do not click a link just because it looks official. Scam links can lead to fake websites that steal your password or personal information.\n\nIf a message claims to be from a company, open the company's official app or website yourself instead of using the link in the message."},
{title:'4. Never Share Private Information',body:'Do not give strangers information such as:\n• Passwords\n• Verification codes\n• Bank or card details\n• Your home address\n• Your school or workplace information\n• Personal identification numbers\n\nA real company should never randomly ask you to send your password.'},
{title:'5. Watch Out for Offers That Seem Too Good to Be True',body:'“Congratulations! You won $5,000!”\n\n“You have been chosen for a free iPhone!”\n\nThese messages are often designed to make people excited so they stop thinking carefully. If you did not enter a competition, it is very unlikely that you suddenly won one.'},
{title:'6. Be Careful with Downloads and Apps',body:'Never download an app or file from a suspicious message or website.\n\nBefore installing an app:\n• Check who created it.\n• Read its reviews.\n• Download it from an official app store.\n• Check what permissions it asks for.\n\nFor example, a calculator app should probably not need access to your contacts, microphone, and messages.'},
{title:'7. Look Carefully at Websites',body:'Fake websites can look almost identical to real ones.\n\nCheck:\n• The website address.\n• Strange spelling in the URL.\n• Poor-quality images or writing.\n• Unexpected pop-ups.\n• Requests for unusual information.\n\nFor example, amaz0n-login.com is not the same as the real Amazon website.'},
{title:'8. Verify Unexpected Messages',body:'Someone may pretend to be your friend, relative, teacher, or another person you trust.\n\nIf someone suddenly messages you from a new number and asks for money, your address, passwords, or private information, verify who they are first.\n\nContact the real person using a number or account you already know.'},
{title:'9. Ask Someone You Trust',body:'If you are unsure, you do not have to make the decision alone.\n\nAsk:\n• A parent\n• A teacher\n• A trusted friend\n• Another responsible adult\n\nIt is better to double-check than to give information to the wrong person.'},
{title:'10. Stop, Check, Then Act',body:'STOP — Do not rush.\nCHECK — Look for warning signs.\nVERIFY — Make sure the person, website, or company is real.\nACT — Only continue when you are sure it is safe.\n\nRemember: scammers depend on people acting quickly. Slow down, check carefully, and never be afraid to ask for help.'}
];
const guideDeck=document.getElementById('guideDeck'),guideCard=document.getElementById('guideCard'),guideNumber=document.getElementById('guideNumber'),guideTitle=document.getElementById('guideTitle'),guideBody=document.getElementById('guideBody'),guideCounter=document.getElementById('guideCounter'),guideProgress=document.getElementById('guideProgress');let currentGuide=0,guideTyping=false,skipGuideTyping=false;
async function typeGuideBody(text){guideTyping=true;skipGuideTyping=false;guideBody.textContent='';for(let i=0;i<text.length;i++){if(skipGuideTyping){guideBody.textContent=text;break}guideBody.textContent+=text[i];await sleep(11)}guideTyping=false}
function loadGuideCard(first=false){const card=guideCards[currentGuide],num=String(currentGuide+1).padStart(2,'0');guideNumber.textContent=num;guideCounter.textContent=`${num} / ${String(guideCards.length).padStart(2,'0')}`;guideProgress.style.width=`${((currentGuide+1)/guideCards.length)*100}%`;guideTitle.textContent=card.title;guideCard.classList.remove('exit','enter');if(!first){void guideCard.offsetWidth;guideCard.classList.add('enter')}typeGuideBody(card.body)}
async function nextGuide(){if(guideTyping){skipGuideTyping=true;return}if(currentGuide>=guideCards.length-1){showScreen('category');return}guideCard.classList.add('exit');await sleep(420);currentGuide++;loadGuideCard()}
guideDeck.addEventListener('click',nextGuide);guideDeck.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();nextGuide()}});

// =========================================================
// ADD OR EDIT SCENARIOS HERE WITH YOUR FRIENDS
// =========================================================
const scenarios={
messages:[
{title:"A Relative You Haven't Heard From",start:'visitor',steps:{visitor:{contact:'Unknown Number',messages:[{from:'them',text:"Heyyy! It's your cousin. I got a new number 😭"},{from:'them',text:"I haven't seen you in forever. What's your home address again? I want to send something."}],choices:[{text:'Send your address because they said they are family.',result:'fail',explanation:'Someone can pretend to be a relative. Your home address is private information, so verify who they are first.'},{text:'Text your mom using the number you already know and ask if this person is really your cousin.',next:'mom'},{text:'Ask the unknown person for more personal family information.',result:'fail',explanation:'A scammer may already know family information from social media. Verify the person through a trusted contact instead.'}]},mom:{contact:'Mom',messages:[{from:'me',text:"Mom, someone with a new number says they're my cousin and wants our address. Is this actually them?"},{from:'them',text:"No. I just called your cousin. That's not their number. Don't reply and block it."}],choices:[{text:"Block the unknown number and don't share anything.",result:'win',explanation:'Perfect. You verified the identity through a trusted person before sharing private information.'},{text:'Reply anyway, just to see what they want.',result:'fail',explanation:'Once you know the account is fake, the safest choice is to stop engaging and block it.'}]}}},
{title:'The Delivery Text',start:'main',steps:{main:{contact:'Unknown Number',messages:[{from:'them',text:'Your package could not be delivered. A 0.500 BHD fee is required.'},{from:'them',text:'Pay now: delivery-update.example'}],choices:[{text:'Open the link because the fee is small.',result:'fail',explanation:'Small payment requests are often used to steal card details on fake delivery websites.'},{text:"Check the order from the shop or delivery company's official app instead.",result:'win',explanation:'Exactly. Check delivery information through an official app, website, or number you already trust.'},{text:'Reply with your card number so they can charge the fee.',result:'fail',explanation:'Never send card details through a random message.'}]}}}
],
emails:[
{title:'Your Account Will Be Deleted',from:'Apple Support <applehelp247@gmail.com>',subject:'URGENT: Your Apple ID will be deleted today',body:'We detected suspicious activity. Confirm your password immediately using the link below or your account will be permanently deleted.',linkText:'VERIFY ACCOUNT NOW',choices:[{text:'Click the email link before the account gets deleted.',result:'fail',explanation:'The message uses urgency and the sender address is suspicious. Do not trust the link.'},{text:"Check the sender address, then open Apple's official app or website yourself.",result:'win',explanation:'Great choice. You checked the warning signs and used an official route instead of the email link.'},{text:'Reply to the email with your password.',result:'fail',explanation:'Never send your password by email.'}]},
{title:'You Won a Prize',from:'Rewards Team <winner.claim.center@outlook.com>',subject:'CONGRATULATIONS! YOU WON A NEW PHONE',body:'You have been selected as today’s lucky winner. To receive your free phone, enter your name, home address, card number and verification code.',linkText:'CLAIM MY PRIZE',choices:[{text:"Claim it because you don't want the prize to expire.",result:'fail',explanation:'A prize you never entered for is a warning sign, especially when it asks for card details.'},{text:'Report the email as phishing and delete it.',result:'win',explanation:'Correct. The sender, unexpected prize, and request for sensitive information are all scam signs.'},{text:'Forward it to friends so they can try too.',result:'fail',explanation:'Forwarding scam messages can expose other people to the same risk.'}]}
],
applications:[
{title:'The Suspicious Calculator',appName:'Ultra Calculator Pro',developer:'Unknown Dev Studio',icon:'⌗',permissions:['Microphone','Contacts','Messages','Precise location'],choices:[{text:'Allow every permission. Apps need access to work.',result:'fail',explanation:'A calculator does not normally need your microphone, contacts, messages, and location.'},{text:'Cancel, check the developer, and choose a trusted calculator from the official app store.',result:'win',explanation:"Exactly. Permissions should make sense for the app's purpose, and the developer should be trustworthy."},{text:'Install it first and remove permissions later.',result:'fail',explanation:'It is safer to check before installing and before giving an app access to your information.'}]},
{title:'A Game From a Random Website',appName:'Galaxy Rush FREE MOD',developer:'Download uploaded by: xX_FreeGames_Xx',icon:'★',permissions:['Install unknown apps','Files and photos','Accessibility controls'],choices:[{text:'Install it because the paid game is free here.',result:'fail',explanation:'Unofficial modified apps can contain malware or steal data.'},{text:'Leave the page and use the official app store instead.',result:'win',explanation:'Correct. Official stores and verified developers are safer than random download pages.'},{text:'Turn off security so the phone lets you install it.',result:'fail',explanation:'Disabling security warnings to install an unknown app increases the risk.'}]}
],
websites:[
{title:'The Virus Pop-up',url:'free-cleaner-now.example/security-check',heading:'⚠ YOUR DEVICE HAS 7 VIRUSES!',text:'Download our cleaner within 30 seconds or your photos may be deleted.',buttonText:'DOWNLOAD CLEANER NOW',choices:[{text:'Download the cleaner immediately.',result:'fail',explanation:'Random websites cannot reliably scan your whole device like this. Scare tactics and countdowns are common scam tricks.'},{text:"Close the page and use your device's official security tools if you are worried.",result:'win',explanation:'Correct. Do not install software from a frightening pop-up.'},{text:'Enter your email so the website can send you the cleaner.',result:'fail',explanation:'Do not give personal information to a suspicious website.'}]},
{title:'The Almost-Correct Login Page',url:'micros0ft-login.example/signin',heading:'Sign in to continue',text:'Your session expired. Enter your school email and password to continue.',buttonText:'SIGN IN',choices:[{text:'Enter your password because the page looks professional.',result:'fail',explanation:'A page can look professional and still be fake. The URL is misspelled.'},{text:'Check the URL carefully and go to the official site yourself instead.',result:'win',explanation:'Exactly. The address matters more than how convincing the page looks.'},{text:'Try an old password first to see if the website accepts it.',result:'fail',explanation:'Do not enter any password into a suspicious page.'}]}
]};

const scenarioHost=document.getElementById('scenarioHost'),gameCategory=document.getElementById('gameCategory'),roundLabel=document.getElementById('roundLabel');let currentCategory='messages',currentScenario=null,currentMessageStep=null;const lastIndex={};
function pretty(s){return s.charAt(0).toUpperCase()+s.slice(1)}function randomScenario(category){const list=scenarios[category];let i=Math.floor(Math.random()*list.length);if(list.length>1&&i===lastIndex[category])i=(i+1)%list.length;lastIndex[category]=i;return list[i]}
function startCategory(category){currentCategory=category;currentScenario=randomScenario(category);gameCategory.textContent=pretty(category);roundLabel.textContent=`random scenario • ${scenarios[category].length} available`;if(category==='messages')currentMessageStep=currentScenario.start;renderScenario();showScreen('game')}
document.querySelectorAll('.category-card').forEach(b=>b.addEventListener('click',()=>startCategory(b.dataset.category)));document.getElementById('backToCategories').addEventListener('click',()=>showScreen('category'));
function renderChoices(choices){return `<div class="choices">${choices.map((c,i)=>`<button class="choice" type="button" data-choice="${i}">${c.text}</button>`).join('')}</div>`}function bindChoices(choices){scenarioHost.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>{const c=choices[Number(b.dataset.choice)];if(c.next){currentMessageStep=c.next;renderMessage();return}showResult(c.result==='win',c.explanation)}))}
function renderScenario(){if(currentCategory==='messages')renderMessage();if(currentCategory==='emails')renderEmail();if(currentCategory==='applications')renderApp();if(currentCategory==='websites')renderWebsite()}
function renderMessage(){const step=currentScenario.steps[currentMessageStep],initial=step.contact.charAt(0).toUpperCase();scenarioHost.innerHTML=`<article class="scenario-shell"><div class="scenario-top"><h2>${currentScenario.title}</h2><p>Choose the reply or action you think is safest.</p></div><div class="scenario-content"><div class="phone-frame"><div class="phone-screen"><div class="notch"></div><div class="contact"><div class="avatar">${initial}</div><div class="contact-name">${step.contact}</div></div><div class="message-area">${step.messages.map(m=>`<div class="bubble ${m.from}">${m.text}</div>`).join('')}<img class="typing-img" src="assets/typing-bubble.png" alt="Typing…"></div><div class="compose">iMessage</div></div></div>${renderChoices(step.choices)}</div></article>`;bindChoices(step.choices)}
function renderEmail(){const s=currentScenario;scenarioHost.innerHTML=`<article class="scenario-shell"><div class="scenario-top"><h2>${s.title}</h2><p>Look closely before you choose what to do.</p></div><div class="scenario-content"><div class="mail"><div class="mail-top"><i></i><i></i><i></i></div><div class="mail-head"><h3>${s.subject}</h3><div class="mail-meta"><b>From:</b> ${s.from}</div></div><div class="mail-body"><p>${s.body}</p><span class="fake-link">${s.linkText}</span></div></div>${renderChoices(s.choices)}</div></article>`;bindChoices(s.choices)}
function renderApp(){const s=currentScenario;scenarioHost.innerHTML=`<article class="scenario-shell"><div class="scenario-top"><h2>${s.title}</h2><p>Decide whether the app request makes sense.</p></div><div class="scenario-content"><div class="app-preview"><div class="app-row"><div class="app-icon">${s.icon}</div><div><h3>${s.appName}</h3><p>${s.developer}</p></div></div><div class="perm"><h4>This app wants permission to access:</h4><ul>${s.permissions.map(p=>`<li>${p}</li>`).join('')}</ul></div></div>${renderChoices(s.choices)}</div></article>`;bindChoices(s.choices)}
function renderWebsite(){const s=currentScenario;scenarioHost.innerHTML=`<article class="scenario-shell"><div class="scenario-top"><h2>${s.title}</h2><p>Look at both the page and the address bar.</p></div><div class="scenario-content"><div class="browser"><div class="browser-top"><div class="url">${s.url}</div></div><div class="site-page"><div class="alert"><h3>${s.heading}</h3><p>${s.text}</p><span class="fake-download">${s.buttonText}</span></div></div></div>${renderChoices(s.choices)}</div></article>`;bindChoices(s.choices)}
const resultPanel=document.getElementById('resultPanel'),resultIcon=document.getElementById('resultIcon'),resultTag=document.getElementById('resultTag'),resultTitle=document.getElementById('resultTitle'),resultMessage=document.getElementById('resultMessage'),resultExplanation=document.getElementById('resultExplanation'),victorySound=document.getElementById('victorySound'),celebration=document.getElementById('celebration');
function showResult(won,explanation){resultPanel.classList.remove('success','fail');resultPanel.classList.add(won?'success':'fail');celebration.classList.toggle('on',won);if(won){resultIcon.textContent='🛡️✨';resultTag.textContent='SAFE CHOICE';resultTitle.textContent='Great job!';resultMessage.textContent='You successfully avoided getting scammed!';if(victorySound){victorySound.pause();victorySound.currentTime=0;victorySound.play().catch(()=>{})}}else{resultIcon.textContent='⚠';resultTag.textContent='SCAMMED';resultTitle.textContent='You got scammed';resultMessage.textContent='You should be more careful next time.';if(victorySound){victorySound.pause();victorySound.currentTime=0}}resultExplanation.textContent=explanation;showScreen('result')}
document.getElementById('retryButton').addEventListener('click',()=>{celebration.classList.remove('on');currentScenario=randomScenario(currentCategory);if(currentCategory==='messages')currentMessageStep=currentScenario.start;renderScenario();showScreen('game')});document.getElementById('resultCategoriesButton').addEventListener('click',()=>{celebration.classList.remove('on');showScreen('category')});